source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PLSelectView_Example', :exclusive => true do
  pod "PLSelectView", :path => "../"
end

target 'PLSelectView_Tests', :exclusive => true do
  pod "PLSelectView", :path => "../"

  pod 'FBSnapshotTestCase'
end
